### ISSUE TITLE
Go 1.13: one shall not call flag.Parse() in init

### ISSUE THREAD

**Issue by eclipseo** [karlseguin/expect#3]
See bug https://github.com/golang/go/issues/33475 and bug https://github.com/golang/go/issues/31859 for the rationale

> To be clear, we are talking only about flag.Parse here, not flag.*. The flag package is designed so that multiple packages can define flags, without those packages being aware of each other. It's essential that flag.Parse be called only after all flags are defined, meaning only after all packages are initialized. The normal practice is that the main package calls flag.Parse, because the main package is the only package that is sure to run after all packages are initialized.
> 
> Your program may well be designed so that it is OK to call flag.Parse in an init function of some non-main package. But most programs do not and cannot work that way. So I am questioning how much we should twist the testing package to support that use case. Of course if the change to the testing package is simple, then that is fine. But I would not like to see a lot of complexity added to support a very unusual use case.

I've read that you don't do much Go anymore, but it would be great if you could keep your package functional for Go 1.13 and further.

**Comment by karlseguin** [comment]
You're right. I haven't done Go in a while. Do you mind taking a look at:
https://github.com/karlseguin/expect/blob/no_init/runner.go#L40

Basically move the init logic into the call to Expectify, guarded by a mutex (probably unecessary, but better safe than sorry I think?)

**Comment by eclipseo** [comment]
I'm not a Go developer only a packager so I can't tell if it's good or not.

**Comment by karlseguin** [comment]
Thanks, I merged. Should be fixed.
